language: python
python:
  - '2.7'
sudo: false
cache:
  directories:
    - "~/.platformio"
install:
  - pip install -U platformio
script:
  - platformio run
before_deploy:
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"s
  - for file in .pioenvs/*/firmware.bin; do cp $file ${file%/*}.bin; done
deploy:
  provider: releases
  api_key:
    secure:  CQmnVWdSDxfsSBSgZ4bPIiquwKulHGhkLE83us+iL9pYri6Co9t/tnniWeH9eDleGEnOfRI5gBfcwRzAv9yrrmiS98uMSTknuM5D7i/X8C+23Tc0vH3sHcEDMgMRI54GVOouXZsFSINTk0Bq8VmyD2D8zh5ln4/PkO+B5koS5D3xgW++Tp7sFh5B7cayI+xUWu3JzLyp9zMUfguqvYjnP+VZGA4C0Yz7WJpBBapwbLPO91el233wwhS8qBml90cReh7A1fOqIYPvj99EBv6sZg3gVSJMT07Vjg0+SZIRbtM3o61zOMAlPY/D2jCTO2BJKBD0NJER4r13Xq05EhQ1yPprEvvs/PO4sZtL/fQOB4EDDOPc4siTcag94kBBW9KgfCx13fkSiN6CzOGVmEs8px/+DNtgF/MCNlnokHPqxm0bDxaEKhOxRrE4oykydvMWQ6n3d4UF1UUydTLYXGpHsZJephxuIX+lCf2cMLXKtZoe7jWpktrVCVd55DjIxBCJtt4Q+uM84OT1/hyPehZ26sp6TcXMtINybDKf7JOpurQ8BWtLrc7PJq+QPAGUGQrKnKPl+YW0x26Y5Bbw1ITb7qacz8IFQcNNBXSyiwntParvRRgYXurSmxwy9xRBiuP5GlHuv/0TYuVt1LvZeNxghbUGZcFfk37uGmhvaF1GW9M=
  file_glob: true
  file: ".pioenvs/*.bin"
  skip_cleanup: true
  on:
    repo: kezzab25/Sonoff-Tasmota
